package Modelos;
// Generated 13-nov-2018 21:06:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private String referencia;
     private String descripcion;
     private BigDecimal stock;
     private BigDecimal precio;

    public Articulos() {
    }

    public Articulos(String referencia, String descripcion, BigDecimal stock, BigDecimal precio) {
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.stock = stock;
       this.precio = precio;
    }
   
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


