package Modelos;
// Generated 13-nov-2018 21:06:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private long codigo;
     private String dni;
     private String nombre;
     private Date fecnac;
     private Set facturases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(long codigo, String dni, String nombre, Date fecnac) {
        this.codigo = codigo;
        this.dni = dni;
        this.nombre = nombre;
        this.fecnac = fecnac;
    }
    public Clientes(long codigo, String dni, String nombre, Date fecnac, Set facturases) {
       this.codigo = codigo;
       this.dni = dni;
       this.nombre = nombre;
       this.fecnac = fecnac;
       this.facturases = facturases;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecnac() {
        return this.fecnac;
    }
    
    public void setFecnac(Date fecnac) {
        this.fecnac = fecnac;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


