package Modelos;
// Generated 13-nov-2018 21:06:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private long nfactura;
     private Clientes clientes;
     private Date fecfactura;
     private BigDecimal total;
     private String pagada;
     private Set linfacturases = new HashSet(0);

    public Facturas() {
    }

	
    public Facturas(long nfactura, Clientes clientes, Date fecfactura, BigDecimal total, String pagada) {
        this.nfactura = nfactura;
        this.clientes = clientes;
        this.fecfactura = fecfactura;
        this.total = total;
        this.pagada = pagada;
    }
    public Facturas(long nfactura, Clientes clientes, Date fecfactura, BigDecimal total, String pagada, Set linfacturases) {
       this.nfactura = nfactura;
       this.clientes = clientes;
       this.fecfactura = fecfactura;
       this.total = total;
       this.pagada = pagada;
       this.linfacturases = linfacturases;
    }
   
    public long getNfactura() {
        return this.nfactura;
    }
    
    public void setNfactura(long nfactura) {
        this.nfactura = nfactura;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Date getFecfactura() {
        return this.fecfactura;
    }
    
    public void setFecfactura(Date fecfactura) {
        this.fecfactura = fecfactura;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getPagada() {
        return this.pagada;
    }
    
    public void setPagada(String pagada) {
        this.pagada = pagada;
    }
    public Set getLinfacturases() {
        return this.linfacturases;
    }
    
    public void setLinfacturases(Set linfacturases) {
        this.linfacturases = linfacturases;
    }




}


