package Modelos;
// Generated 13-nov-2018 21:06:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Linfacturas generated by hbm2java
 */
public class Linfacturas  implements java.io.Serializable {


     private long id;
     private Facturas facturas;
     private String referencia;
     private BigDecimal cantidad;
     private BigDecimal descuento;

    public Linfacturas() {
    }

    public Linfacturas(long id, Facturas facturas, String referencia, BigDecimal cantidad, BigDecimal descuento) {
       this.id = id;
       this.facturas = facturas;
       this.referencia = referencia;
       this.cantidad = cantidad;
       this.descuento = descuento;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }




}


